CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE Users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);